//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesforceSQLSchemaGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SalesforceUrl {
            get {
                return ((string)(this["SalesforceUrl"]));
            }
            set {
                this["SalesforceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SalesforceUsername {
            get {
                return ((string)(this["SalesforceUsername"]));
            }
            set {
                this["SalesforceUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SalesforcePassword {
            get {
                return ((string)(this["SalesforcePassword"]));
            }
            set {
                this["SalesforcePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SalesforceToken {
            get {
                return ((string)(this["SalesforceToken"]));
            }
            set {
                this["SalesforceToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbo")]
        public string SqlSchemaName {
            get {
                return ((string)(this["SqlSchemaName"]));
            }
            set {
                this["SqlSchemaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SqlTextUnicode {
            get {
                return ((bool)(this["SqlTextUnicode"]));
            }
            set {
                this["SqlTextUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SqlVarcharMaxMinimumThreshold {
            get {
                return ((string)(this["SqlVarcharMaxMinimumThreshold"]));
            }
            set {
                this["SqlVarcharMaxMinimumThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalesforceRememberConnection {
            get {
                return ((bool)(this["SalesforceRememberConnection"]));
            }
            set {
                this["SalesforceRememberConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlSaveDirectory {
            get {
                return ((string)(this["SqlSaveDirectory"]));
            }
            set {
                this["SqlSaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SqlGenerateForeignKeys {
            get {
                return ((bool)(this["SqlGenerateForeignKeys"]));
            }
            set {
                this["SqlGenerateForeignKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalesforceRememberSelectedObjects {
            get {
                return ((bool)(this["SalesforceRememberSelectedObjects"]));
            }
            set {
                this["SalesforceRememberSelectedObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SalesforceSelectedObjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SalesforceSelectedObjects"]));
            }
            set {
                this["SalesforceSelectedObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SqlGenerateForeignKeysSelectedObjectsOnly {
            get {
                return ((bool)(this["SqlGenerateForeignKeysSelectedObjectsOnly"]));
            }
            set {
                this["SqlGenerateForeignKeysSelectedObjectsOnly"] = value;
            }
        }
    }
}
